config/routes.rb
BigTuna::Application.routes.draw do
  if BigTuna.read_only?

    resources :projects, :only => [:index, :show] do
      member { get "feed" }
    end
    resources :builds, :only => [:show]

  else

    resources :projects do
      member { get "build"; get "remove"; get "arrange"; get "feed"; get "duplicate" }
      match "/hooks/:name/configure", :to => "hooks#configure", :as => "config_hook"
    end
    resources :builds
    resources :step_lists
    resources :shared_variables

  end

  match "/hooks/build/:hook_name", :to => "hooks#autobuild"
  match "/hooks/build/github/:secure", :to => "hooks#github"
  match "/hooks/build/bitbucket/:secure", :to => "hooks#bitbucket"
  root :to => "projects#index"
end

app/models/build.rb
class Build < ActiveRecord::Base
  STATUS_IN_QUEUE = "status_build_in_queue"
  STATUS_PROGRESS = "status_build_in_progress"
  STATUS_OK = "status_build_ok"
  STATUS_FAILED = "status_build_failed"
  STATUS_BUILDER_ERROR = "status_builder_error"
  STATUS_HOOK_ERROR = "status_hook_error"

  belongs_to :project
  has_many :parts, :class_name => "BuildPart"

  before_destroy :remove_build_dir
  before_create :set_build_values
  serialize :output, Array

  def ajax_reload?
    case BigTuna.ajax_reload
    when "always" then true
    when "building" then [STATUS_IN_QUEUE, STATUS_PROGRESS].include?(self.status)
    else false
    end
  end

  def perform
    self.update_attributes!(:status => STATUS_PROGRESS)
    self.started_at = Time.now
    project = self.project
    begin
      out = fetch_project_sources(project)
      self.update_attributes!(vcs.head_info[0].merge(:output => [out]))
      vcs_ok = true
    rescue BigTuna::Runner::Error => e
      self.status = STATUS_FAILED
      self.output = [e.output]
      self.save!
      vcs_ok = false
    end
    run_build_parts() if vcs_ok
  end

  def display_name
    "Build ##{self.build_no} @ #{I18n.l(self.scheduled_at, :format => :long)}"
  end

  def to_param
    [self.id, self.project.name.to_url, self.display_name.to_url].join("-")
  end

  def started?
    ! started_at.nil?
  end

  def commit_data?
    self.author && self.email && self.commit_message && self.committed_at && self.commit
  end

  def finished?
    ! finished_at.nil?
  end

  def vcs
    return @vcs if @vcs
    vcs_type = self.project.vcs_type
    vcs_branch = self.project.vcs_branch
    klass = BigTuna.vcses.find { |e| e::VALUE == vcs_type }
    raise ArgumentError.new("VCS not supported: %p" % [vcs_type]) if klass.nil?
    @vcs = klass.new(self.build_dir, vcs_branch)
  end

  def update_part(part)
    if parts.where(:finished_at => nil).count == 0 # build finished
      statuses = parts.map { |p| p.status }
      status = statuses.all? { |e| e == BuildPart::STATUS_OK } ? STATUS_OK : STATUS_FAILED
      self.update_attributes!(:finished_at => Time.now, :status => status)
      if status != STATUS_OK
        new_failed_builds = project.failed_builds + 1
        project.update_attributes!(:failed_builds => new_failed_builds)
        after_failed()
      else
        after_passed()
      end
      after_finished()
    end
    project.truncate_builds!
  end

  private
  def remove_build_dir
    if project.fetch_type == :clone
      if File.directory?(self.build_dir)
        FileUtils.rm_rf(self.build_dir)
      else
        BigTuna.logger.info("Couldn't find build dir to remove: %p" % [self.build_dir])
      end
    end
  end

  def set_build_values
    project_dir = project.build_dir
    self.build_dir = compute_build_dir
    self.status = STATUS_IN_QUEUE
    self.scheduled_at = Time.now
    self.output = []
  end

  def run_build_parts
    if self.project.step_lists.empty?
      self.update_attributes!(:status => STATUS_OK)
      after_passed()
      after_finished()
    else
      self.project.step_lists.each do |step_list|
        replacements = {}
        step_list.shared_variables.all.each { |var| replacements[var.name] = var.value }
        replacements["build_dir"] = self.build_dir
        replacements["project_dir"] = self.project.build_dir
        attrs = {
          :name => step_list.name,
          :steps => step_list.steps,
          :shared_variables => replacements,
        }
        part = self.parts.build(attrs)
        part.save!
        part.build!
      end
    end
  end

  def after_passed
    previous_build = self.project.builds.order("created_at DESC").offset(1).first
    build_fixed = (status == STATUS_OK && previous_build && previous_build.status == STATUS_FAILED)
    build_still_passes = (status == STATUS_OK && previous_build && previous_build.status == STATUS_OK)
    project.hooks.each do |hook|
      hook.build_passed(self)
      hook.build_still_passes(self) if build_still_passes
      hook.build_fixed(self) if build_fixed
    end
  end

  def after_failed
    previous_build = self.project.builds.order("created_at DESC").offset(1).first
    build_failed = (previous_build.nil? or (previous_build && previous_build.status == STATUS_OK))
    build_still_fails = (previous_build and previous_build.status != STATUS_OK)
    project.hooks.each do |hook|
      hook.build_failed(self) if build_failed
      hook.build_still_fails(self) if build_still_fails
    end
  end

  def after_finished
    previous_build = self.project.builds.order("created_at DESC").offset(1).first
    project.hooks.each do |hook|
      hook.build_finished(self)
    end
  end
  
  def compute_build_dir
    if project.fetch_type == :incremental
      File.join(project.build_dir, "checkout")
    else
      File.join(project.build_dir, "build_#{self.build_no}_#{self.scheduled_at.strftime("%Y%m%d%H%M%S")}")
    end
  end
  
  def fetch_project_sources(project)
    case project.fetch_type
    when :clone
      fetch_project_sources_by_cloning
    when :incremental
      fetch_project_sources_incrementally
    end
  end
  
  def fetch_project_sources_incrementally
    if project_sources_already_present?
      update_project
    else
      fetch_project_sources_by_cloning
    end
  end
  
  def fetch_project_sources_by_cloning
    clone_project
  end
  
  def clone_project
    project.vcs.clone(self.build_dir)
  end
  
  def update_project
    project.vcs.update(self.build_dir)
  end
  
  def project_sources_already_present?
    File.directory? self.build_dir 
  end
end

app/controllers/builds_controller.rb
class BuildsController < ApplicationController
  before_filter :locate_build, :only => [:show, :destroy]
  respond_to :js, :only => :show

  def show

  end

  def destroy
    project = @build.project
    @build.destroy
    redirect_to project_path(project)
  end

  private
  def locate_build
    @build = Build.find(params[:id])
  end
end

app/views/builds/_build.html.haml
.build-details
  - if build.output[0]
    %h3{ :class => build.output[0].exit_code == 0 ? "status_build_ok" : "status_build_failed"}
      VCS
    %ul.unstyled
      %li
        = render :partial => "builds/step", :locals => {:step => build.output[0], :step_no => 0}
  - build.parts.each_with_index do |part, index|
    %h3{ :class => part.output[0].nil? ? "" : (part.output[0].exit_code == 0 ? "status_build_ok" : "status_build_failed") }
      = part.name
    %ul{:id => "part_#{index}", :class => 'unstyled' }
      - part.output.each_with_index do |output, index|
        %li{:id => "step_#{index + 1}"}
          = render :partial => "builds/step", :locals => {:step => output, :step_no => index + 1}
      - if build.status == Build::STATUS_PROGRESS
        %li{ :class => Build::STATUS_PROGRESS }
          %div.pulse
          %span.label.warning Building

app/views/builds/_build_data.html.haml
.commit-detail
  %span.label Commit
  %code.commit= build.commit_data? ? build.commit : "Commit hash not yet available"
  %br
  %span.label Author
  = build.commit_data? ? (mail_to(build.email, build.author)).html_safe : "Author not yet available"
  %br
  %span.label Date
  = build.commit_data? ? l(build.committed_at, :format => :long) : "Commit date not yet available"
  %blockquote
    = build.commit_data? ? build.commit_message : "Message not yet available"

app/views/builds/_build_details.html.haml
%table.table
  %thead
    %tr
      %th{:style => 'width: 10%'}
      %th{:style => 'width: 90%'}

  %tbody
    %tr
      %td
        %span.label.label-info Commit
      %td
        %code.dark= @build.commit_data? ? @build.commit : "Commit hash not yet available"
    %tr
      %td
        %span.label.label-info Author
      %td= @build.commit_data? ? (mail_to(@build.email, @build.author)).html_safe : "Author not yet available"
    %tr
      %td
        %span.label.label-info Date
      %td= @build.commit_data? ? l(@build.committed_at, :format => :long) : "Commit date not yet available"
    %tr
      %td
        %span.label.label-info Message
      %td
        %pre.unobstrusive= @build.commit_data? ? @build.commit_message : "Message not yet available"
    %tr
      %td
        %span.label.label-info Scheduled
      %td
        = time_ago_in_words(@build.scheduled_at)
        ago
    - if @build.started?
      %tr
        %td
          %span.label.label-info Started
        %td
          = time_ago_in_words(@build.started_at)
          ago

    - if @build.finished?
      %tr
        %td
          %span.label.label-info Duration
        %td
          = build_duration(@build)
    %tr
      %td
        %span.label.label-info Directory
      %td
        %code.dark= truncate(strip_rails_root(@build.build_dir), :length => 40, :omission => '..')

app/views/builds/_step.html.haml
%div{:id => "step_outer_#{step_no}", :class => step.exit_code == 0 ? "status_build_ok output_box" : "status_build_failed output_box"}
  - unless step.exit_code == 0
    %span.label.label-important FAILED
  - if step.exit_code.nil?
    %samp.command= "Task was not executed"
  - elsif step.exit_code != 0
    %samp.command= "Exit code: <strong>#{step.exit_code}</strong>".html_safe
  %pre{:class => step.exit_code == 0 ? 'code' : 'code failed'}
    %p.command= "$ #{step.command}"
    - if !step.exit_code.nil? and step.has_output?
      - step.all.each do |type, text|
        - if ((type != BigTuna::Runner::Output::TYPE_STDERR or params[:stderr]) and !text.empty?)
          = strip_shell_colorization(text)
%br

app/views/builds/show.html.haml
.page-header
  %h1
    = @build.project.name
    = "##{@build.build_no}"
    %small
      via
      %code.dark= @build.project.vcs_source
      on
      %code.dark= @build.project.vcs_branch
    - unless BigTuna.read_only?
      = link_to("Build now", build_project_path(@build.project), :class => "btn crm btn-large btn-success pull-right")

  .btn-group.light
    - if params[:stderr].nil?
      = link_to("Show stderr", build_path(@build, :stderr => 1), :class => "btn btn-warning")
    - else
      = link_to("Hide stderr", build_path(@build), :class => "btn btn-warning")
    - unless BigTuna.read_only?
      = link_to("Edit project", edit_project_path(@build.project), :class => "btn")
      = form_tag(build_path(@build), :method => "DELETE") do
        %button{:class => 'btn btn-danger', :type => "submit"} Delete build


#build.row
  .span8
    #ajax-reload= @build.ajax_reload?

    = render :partial => 'build', :locals => { :build => @build }

    - unless @build.finished?
      - build_path_params = params[:stderr] ? {:format => :js, :stderr => 1} : {:format => :js}
      = ajaxReload(build_path(@build, build_path_params))
  .span4
    - unless BigTuna.read_only?
      %div.project-actions
        - unless BigTuna.read_only?
          = render :partial => 'build_details'

- content_for :topbar do
  %li= link_to("#{@build.project.name} home", project_path(@build.project))
  %li= link_to("", feed_project_path(@project, :format => "atom"), :class => "rss")

app/views/builds/show.js.erb
$("#build").html("<%= escape_javascript(render(:partial => 'build')) %>");