config/routes.rb
BigTuna::Application.routes.draw do
  if BigTuna.read_only?

    resources :projects, :only => [:index, :show] do
      member { get "feed" }
    end
    resources :builds, :only => [:show]

  else

    resources :projects do
      member { get "build"; get "remove"; get "arrange"; get "feed"; get "duplicate" }
      match "/hooks/:name/configure", :to => "hooks#configure", :as => "config_hook"
    end
    resources :builds
    resources :step_lists
    resources :shared_variables

  end

  match "/hooks/build/:hook_name", :to => "hooks#autobuild"
  match "/hooks/build/github/:secure", :to => "hooks#github"
  match "/hooks/build/bitbucket/:secure", :to => "hooks#bitbucket"
  root :to => "projects#index"
end

app/models/project.rb
class Project < ActiveRecord::Base
  STATUS_NOT_BUILT = "status_not_built"
  attr_accessor :hook_update

  has_many :builds, :dependent => :destroy
  has_many :step_lists, :dependent => :destroy
  before_destroy :remove_build_folder
  before_update :rename_build_folder
  before_create :set_default_build_counts
  after_save :update_hooks
  
  validates :hook_name, :uniqueness => {:allow_blank => true}
  validates :name, :presence => true, :uniqueness => true
  validates :vcs_type, :inclusion => BigTuna.vcses.map { |e| e::VALUE }
  validates :vcs_source, :presence => true
  validates :vcs_branch, :presence => true
  
  validate :validate_vcs_incremental_support
  
  acts_as_list

  def self.ajax_reload?
    case BigTuna.ajax_reload
    when "always" then true
    when "building" then self.all.map(&:recent_build).compact.map(&:ajax_reload?).include?(true)
    else false
    end
  end

  def duplicate_project
    project_clone = self.clone
    project_clone.name += " COPY"

    if !self.hook_name.blank?
      project_clone.update_attributes({:hook_name => self.hook_name + "_copy"})
    end

    if !project_clone.save!
      return nil
    end

    self.step_lists.each do |step_list|
      new_step_list = step_list.clone
      new_step_list.project = project_clone
      new_step_list.save
    end

    project_clone
  end

  def ajax_reload?
    case BigTuna.ajax_reload
    when "always" then true
    when "building" then self.recent_build.try(:ajax_reload?)
    else false
    end
  end

  def recent_build
    builds.order("created_at DESC").first
  end

  def build!
    new_total_builds = self.total_builds + 1
    ActiveRecord::Base.transaction do
      build = self.builds.create!({:scheduled_at => Time.now, :build_no => new_total_builds})
      self.update_attributes!(:total_builds => new_total_builds)
      remove_project_jobs_in_queue()
      Delayed::Job.enqueue(build)
    end
  end

  def hooks
    hook_hash = {}
    BigTuna.hooks.each do |hook|
      hook_hash[hook::NAME] = hook
    end
    Hook.where(:project_id => self.id)
  end

  def build_dir
    build_dir_from_name(name)
  end

  def truncate_builds!
    builds.order("created_at DESC").offset(self.max_builds).each do |build|
      build.destroy
    end
  end

  def max_builds
    super || 10
  end

  def status
    build = recent_build
    build.nil? ? STATUS_NOT_BUILT : build.status
  end

  def vcs
    return @vcs if @vcs
    klass = BigTuna.vcses.find { |e| e::VALUE == vcs_type }
    raise ArgumentError.new("VCS not supported: %p" % [vcs_type]) if klass.nil?
    @vcs = klass.new(self.vcs_source, self.vcs_branch)
  end

  def to_param
    [self.id, self.name.to_url].join("-")
  end

  def stability
    last_builds = builds.order("created_at DESC").
      where(:status => [Build::STATUS_OK, Build::STATUS_FAILED, Build::STATUS_BUILDER_ERROR]).
      limit(5)
    statuses = last_builds.map { |e| e.status }
    return -1 if statuses.size < 5
    statuses.count { |e| e == Build::STATUS_OK }
  end

  def hooks=(hooks)
    @_hooks = hooks
  end
  
  def fetch_type
    if self[:fetch_type]
      self[:fetch_type].to_sym
    else
      :clone
    end
  end
  
  private
  def build_dir_from_name(name)
    if BigTuna.build_dir[0] == '/'[0]
      File.join(BigTuna.build_dir, name.downcase.gsub(/[^A-Za-z0-9]/, "_"))
    else
      File.join(Rails.root, BigTuna.build_dir, name.downcase.gsub(/[^A-Za-z0-9]/, "_"))
    end
  end

  def remove_build_folder
    if File.directory?(self.build_dir)
      FileUtils.rm_rf(self.build_dir)
    else
      Rails.logger.debug("[BigTuna] Couldn't find build dir: %p" % [self.build_dir])
    end
  end

  def rename_build_folder
    if self.name_changed? && self.total_builds != 0
      old_dir = build_dir_from_name(self.name_was)
      new_dir = build_dir_from_name(self.name)
      FileUtils.mv(old_dir, new_dir)
    end
  end

  def set_default_build_counts
    self.total_builds = 0
    self.failed_builds = 0
  end

  def update_hooks
    return unless self.hook_update
    new_hooks = (@_hooks || {}).keys
    current_hooks = self.hooks.map { |e| e.hook_name }
    to_remove = current_hooks - new_hooks
    to_add = new_hooks - current_hooks
    Hook.where(:project_id => self.id, :hook_name => to_remove).delete_all
    to_add.each do |name|
      Hook.create!(:project => self, :hook_name => name)
    end
  end

  def remove_project_jobs_in_queue
    jobs_to_destroy = []
    Delayed::Job.all.each do |job|
      build = job.payload_object
      next unless build.is_a?(Build)
      if build.status = Build::STATUS_IN_QUEUE && build.project == self
        jobs_to_destroy << job
      end
    end
    jobs_to_destroy.each { |job| job.destroy }
  end
  
  def validate_vcs_incremental_support
    errors.add(:fetch_type, " #{fetch_type} not support by the vcs") if fetch_type == :incremental && !vcs.support_incremental_build?
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_filter :locate_project, :only => [:show, :build, :edit, :update, :remove, :destroy, :arrange, :feed, :duplicate]
  respond_to :js, :only => [:index, :show]


  def index
    @projects = Project.order("position ASC")
  end

  def show
    @builds = @project.builds.order("created_at DESC").limit(@project.max_builds).includes(:project, :parts).all
  end

  def feed
    @builds = @project.builds.order("created_at DESC").limit(@project.max_builds)
    respond_to do |format|
      format.atom
    end
  end

  def build
    @project.build!
    redirect_to(project_path(@project))
  rescue BigTuna::VCS::Error => e
    flash[:error] = e.message
    redirect_to project_path(@project)
  end

  def duplicate
    project_clone = @project.duplicate_project
    redirect_to project_path(project_clone)
  rescue ActiveRecord::RecordInvalid => e
    flash[:error] = e.message
    redirect_to project_path(@project)
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(params[:project])
    if @project.save
      redirect_to edit_project_path(@project)
    else
      render :new
    end
  end

  def edit
  end

  def update
    @project.update_attributes!(params[:project])
    redirect_to edit_project_path(@project)
  end

  def remove
  end

  def destroy
    @project.destroy
    redirect_to projects_path
  end

  def arrange
    if params[:up]
      @project.move_higher
    elsif params[:down]
      @project.move_lower
    end
    redirect_to projects_path
  end

  private
  def locate_project
    @project = Project.find(params[:id])
  end
end

app/views/projects/_builds.html.haml
%ul.list-with-status.in-recent-builds
  - @builds.each do |build|
    .span4.offset1
      %h1{:class => "project-title #{build.status}"}= link_to("Build ##{build.build_no}", build_path(build, :stderr => build.status == Build::STATUS_OK ? nil : 1))

    .span6
      %table.table.commit-data
        %thead
          %tr
            %th{:style => 'width: 20%'}
            %th{:style => 'width: 80%'}
        %tbody
          %tr
            %td Commit
            %td
              - if build.commit_data?
                %code{:class => "dark", :title => build.commit}= truncate(build.commit, :length => 10, :omission => '..')
                by
                = (mail_to(build.email, build.author)).html_safe
                = " on #{l(build.committed_at, :format => :long)}"
              - else
                Commit data not yet available
          %tr
            %td Message
            %td
              %pre.unobstrusive= build.commit_data? ? build.commit_message : "Message not yet available"
    .span12
      %hr

app/views/projects/_form.html.haml
- if f.object.errors.any?
  - f.object.errors.full_messages.each do |msg|
    %p= msg

.control-group
  = f.label(:name, :class => 'control-label')
  .controls
    = f.text_field(:name)

.control-group
  = f.label(:vcs_type, :class => 'control-label')
  .controls
    = f.select(:vcs_type, BigTuna.vcses.map { |klass| [klass::NAME, klass::VALUE] }, :class => 'textfield')

.control-group
  = f.label(:vcs_source, :class => 'control-label')
  .controls
    = f.text_field(:vcs_source, :class => 'span4')
    %p.help-block Typically the address of your repo

.control-group
  = f.label(:vcs_branch, :class => 'control-label')
  .controls
    = f.text_field(:vcs_branch)
    %p.help-block  Branch for BigTuna to pull from


.control-group
  = f.label(:fetch_type, :class => 'control-label')
  .controls
    %label.radio
      = f.radio_button(:fetch_type, :clone)
      Clone
    %span.help-block Will set up a brand new copy of the repo every time
    %label.radio
      = f.radio_button(:fetch_type, :incremental)
      Incremental
    %span.help-block Will build over the previous build (saves time)


.control-group
  = f.label(:max_builds, :class => 'control-label')
  .controls
    = f.text_field(:max_builds, :class => 'span1')
    %p.help-block How many builds to keep in memory

.control-group
  %label Hooks
  .controls
    - BigTuna.hooks.each do |hook|
      %div{:id => "hook_#{hook::NAME}", :class => "hint"}
        %label{:class => 'checkbox', :for => "project_hooks_#{hook::NAME}"}
          = check_box_tag("project[hooks][#{hook::NAME}]", hook::NAME, f.object.hooks.map { |e| e.hook_name }.include?(hook::NAME))
          = hook::NAME
        = link_to("Configure", project_config_hook_path(f.object, hook::NAME)) if f.object.hooks.map { |e| e.hook_name }.include?(hook::NAME)

.control-group
  = f.label(:hook_name, :class => 'control-label')
  .controls
    = f.text_field(:hook_name)
    %p.help-block POST to http://big.tuna.host/hooks/build/:hook_name: to build automatically
    = f.hidden_field(:hook_update, {:value => true})

.form-actions
  %button.btn.btn-primary{:type => "submit"}
    = f.object.new_record? ? "Create project" : "Update"
  = link_to("Back to project", project_path(f.object), :class => "btn") unless f.object.new_record?

app/views/projects/_projects.html.haml
#ajax-reload= Project.ajax_reload?
- if @projects.empty?
  .hero-unit
    %h1= "No projects yet."
    %p
      Add a new project and start continuously testing your software!
    %p
      = link_to("Set up a new project", new_project_path, :class => 'btn btn-primary btn-large jumbo')

- @projects.each do |project|
  %div{:class => 'row', :id => dom_id(project)}
    - unless BigTuna.read_only?
      .updown
        = link_to("&uarr;".html_safe, arrange_project_path(project, :up => true)) unless project.first?
        = link_to("&darr;".html_safe, arrange_project_path(project, :down => true)) unless project.last?
    .span3.offset2
      %h1{:class => "project-title #{project.status}"}
        = link_to(project.name, project_path(project))

    .span5.offset1
      - if project.recent_build
        - build = project.recent_build
        %table.table.commit-data
          %thead
            %tr
              %th{:style => 'width: 20%'}
              %th{:style => 'width: 80%'}
          %tbody
            %tr
              %td Commit
              %td
                - if build.commit_data?
                  %code{:class => "dark", :title => build.commit}= truncate(build.commit, :length => 10, :omission => '..')
                  by
                  = (mail_to(build.email, build.author)).html_safe
                  = " on #{l(build.committed_at, :format => :long)}"
                - else
                  Commit data not yet available
            %tr
              %td Message
              %td
                %pre.unobstrusive= build.commit_data? ? build.commit_message : "Message not yet available"
            %tr
              %td Stability
              %td= format_stability(project.stability)

app/views/projects/edit.html.haml
.page-header
  %h1
    = @project.name
    %small Edit project options and configurations
    - unless BigTuna.read_only?
      = link_to("Build now", build_project_path(@project), :class => "btn crm btn-large btn-success pull-right")

.row
  .span6
    %h2 Edit project
    = form_for(@project, :url => project_path(@project), :html => { :class => 'form-horizontal'}) do |f|
      = render :partial => "form", :locals => {:f => f}
  .span6.right-column
    %h2 Edit configurations

    %div.hint
      Special variables are available.
      %ul
        %li= "<tt><b>%build_dir%</b> directory where build is checked out</tt>".html_safe
        %li= "<tt><b>%project_dir%</b> directory shared by all builds in project</tt>".html_safe
      %span.help-block= "You can comment a step with <tt>#</tt>".html_safe

    - unless @project.step_lists.empty?
      - @project.step_lists.each do |step_list|
        %hr
        %h3.step-list-header= step_list.name
        - unless step_list.new_record?
          = form_for(step_list, :url => step_list_path(step_list, :project_id => @project), :html => {:method => "DELETE", :id => "remove_step_list_#{step_list.id}"}) do |f|
            %button{:class => 'btn btn-danger btn-small btn-tiny btn-shared-variable-removal' , :type => "submit"} Remove
        %div.hint
          %ul
            - step_list.shared_variables.each do |variable|
              %li= "<tt><b>%#{variable.name}%</b> #{variable.value}</tt>".html_safe
          = link_to("Edit configuration specific variables", shared_variables_path(:step_list_id => step_list), :class => 'pull-up')
        = form_for(step_list, :url => step_list_path(step_list, :project_id => @project), :html => { :class => 'form-horizontal', :method => "PUT"}) do |f|
          = render :partial => "step_lists/form", :locals => {:f => f}

    %h3 New configuration
    = form_for(StepList.new, :url => step_lists_path(:project_id => @project), :html => { :class => 'form-horizontal'}) do |f|
      = render :partial => "step_lists/form", :locals => {:f => f}





- content_for :topbar do
  - unless BigTuna.read_only?
    %li= link_to("#{@project.name}", project_path(@project), :class => "black_button")

app/views/projects/index.html.haml
= render :partial => 'projects'

= ajaxReload(projects_path(:format => :js))

- content_for :topbar do
  - unless BigTuna.read_only?
    %li= link_to("New Project", new_project_path)

app/views/projects/index.js.erb
$("#listing").html("<%= escape_javascript(render(:partial => 'projects')) %>");

app/views/projects/new.html.haml
.page-header
  %h1
    Set up a new project
    %small Provide BigTuna with all the necessary data to set up a project.

= form_for(@project, :url => projects_path, :html => { :class => 'form-horizontal'}) do |f|
  = render :partial => "form", :locals => {:f => f}

app/views/projects/remove.html.haml
%h2= "Removing #{@project.name}"
%p Are you sure?
= form_for(@project, project_path(@project), :html => {:method => "DELETE"}) do
  %button.crit_button{:type => "submit"} Yes, I'm sure
  = link_to("No, thanks", project_path(@project), :class => "black_button")

app/views/projects/show.html.haml
.page-header
  %h1
    = @project.name
    %small
      via
      %code.dark= @project.vcs_source
      on
      %code.dark= @project.vcs_branch
    - unless BigTuna.read_only?
      = link_to("Build now", build_project_path(@project), :class => "btn crm btn-large btn-success pull-right")
    .btn-toolbar
      - unless BigTuna.read_only?
        .btn-group.light
          = link_to("Edit project", edit_project_path(@project), :class => "btn")
          = link_to("Duplicate project", duplicate_project_path(@project), :class => "btn")
          = link_to("Remove project", remove_project_path(@project), :class => "btn btn-danger")
      .btn-group.light
        = link_to("RSS Feed", feed_project_path(@project, :format => "atom"), :class => "btn btn-warning")


- if @project.builds.any?
  = render :partial => 'builds'
- else
  .row
    .span12
      .hero-unit
        %h1= "No builds yet."
        %p
          Press the Build now button to start a build!

  .span4
    - if @project.builds.any?
      %ul.part-status
        - if @project.builds.last.parts.empty?
          %li
            %span{ :class => "label notice" } Queued
        - @project.builds.last.parts.each_with_index do |part, index|
          %li
            %span{ :class => "label #{status_css_class(part.status)}" }
              = link_to(formatted_status(part.status), build_path(@project.builds.last, :stderr => @project.builds.last.status == Build::STATUS_OK ? nil : 1, :anchor => "part_#{index}"))
            %span.name
              = part.name
      = ajaxReload(project_path(@project, :format => :js))

app/views/projects/show.js.erb
$("#builds").html("<%= escape_javascript(render(:partial => 'builds')) %>");