config/routes.rb
BigTuna::Application.routes.draw do
  if BigTuna.read_only?

    resources :projects, :only => [:index, :show] do
      member { get "feed" }
    end
    resources :builds, :only => [:show]

  else

    resources :projects do
      member { get "build"; get "remove"; get "arrange"; get "feed"; get "duplicate" }
      match "/hooks/:name/configure", :to => "hooks#configure", :as => "config_hook"
    end
    resources :builds
    resources :step_lists
    resources :shared_variables

  end

  match "/hooks/build/:hook_name", :to => "hooks#autobuild"
  match "/hooks/build/github/:secure", :to => "hooks#github"
  match "/hooks/build/bitbucket/:secure", :to => "hooks#bitbucket"
  root :to => "projects#index"
end

app/models/shared_variable.rb
class SharedVariable < ActiveRecord::Base
  belongs_to :step_list
end

app/controllers/shared_variables_controller.rb
class SharedVariablesController < ApplicationController
  before_filter :fetch_step_list

  def index
    @shared_variables = @step_list.shared_variables
    @shared_variable = SharedVariable.new(params[:shared_variable])
  end

  def create
    @shared_variable = SharedVariable.new(params[:shared_variable])
    @shared_variable.step_list = @step_list
    @shared_variable.save!
    redirect_to shared_variables_path(:step_list_id => @step_list)
  end

  def update
    @shared_variable = SharedVariable.find(params[:id])
    @shared_variable.update_attributes!(params[:shared_variable])
    redirect_to shared_variables_path(:step_list_id => @step_list)
  end

  def destroy
    @shared_variable = SharedVariable.find(params[:id])
    @shared_variable.destroy
    redirect_to shared_variables_path(:step_list_id => @step_list)
  end

  private
  def fetch_step_list
    @step_list = StepList.find(params[:step_list_id])
  end
end

app/helpers/shared_variables_helper.rb
module SharedVariablesHelper
end

app/views/shared_variables/index.html.haml
.page-header
  %h1= "Shared variables for &quot;#{@step_list.project.name}&quot;".html_safe

%p You can set up configuration&ndash;specific <tt>%variables%</tt> here. Real&ndash;life examples would be
%ul
  %li= "<tt><b>%runner%</b> rvm 1.8.7 exec</tt>".html_safe
  %li= "<tt><b>%envs%</b> env RAILS_ENV=test BUNDLE_GEMFILE=%build_dir%/Gemfile</tt>".html_safe

%p And then use them in steps like:

<pre>cp /shared/config.yml %build_dir%/config/
\%runner% %envs% bundle install --deployment --path=%project_dir%/bundle
\%runner% %envs% bundle exec rake db:migrate
\%runner% %envs% bundle exec rake</pre>

%p Shared variables cannot contain other shared variables except <tt>%build_dir%</tt> and <tt>%project_dir%</tt>.

.row
  .span6
    %h3
      Create new variable
    %p.help-block Specify the name and the value
    = form_for(@shared_variable, :url => shared_variables_path(:step_list_id => @step_list), :html => { :class => 'form-horizontal'}) do |f|
      .control-group
        = f.label(:name)
        .controls
          = f.text_field(:name)
      .control-group
        = f.label(:value)
        .controls
          = f.text_field(:value)
      .form-actions
        %button{:type => "submit", :class => 'btn btn-primary'}
          = f.object.new_record? ? "Create" : "Update"
  .span6
    - unless @shared_variables.empty?
      %h3 Already existing variables
      - @shared_variables.each do |variable|
        %hr
        %h3= variable.name
        = form_for(variable, :url => shared_variable_path(variable, :step_list_id => @step_list), :html => {:method => :delete}) do |f|
          %button{:class => 'btn btn-danger btn-small btn-tiny btn-shared-variable-removal', :type => "submit"} Remove 
        = form_for(variable, :url => shared_variable_path(variable, :step_list_id => @step_list), :html => { :class => 'form-horizontal'}) do |f|
          .control-group
            = f.label(:name)
            .controls
              = f.text_field(:name)
          .control-group
            = f.label(:value)
            .controls
              = f.text_field(:value)
          .form-actions
            %button{:class => 'btn btn-primary', :type => "submit"} Update